name: 'Setup Python Dependencies'
description: 'Set up Python and install dependencies for a project'
inputs:
  cache-hit:
    description: 'Whether the cache hit or not'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [[ "${{ inputs.cache-hit }}" != 'false' ]]; then
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
        fi
      shell: bash
