name: 'Setup Python and Dependencies'
description: 'Set up Python and install dependencies for a project'
inputs:
  python-version:
    description: 'Version of Python to set up'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.python-version }}"

    - name: Upgrade pip
      run: python3 -m pip install --upgrade pip
      shell: bash

