name: Build Workflow

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'

permissions:
  id-token: write
  contents: write

jobs:
  build-pheno-utils:
    uses: PhenoAI/ci_cd_shared_infrastructure/.github/workflows/build_docker_image.yml@main
    with:
      image_name: "pheno_utils"
    secrets: inherit
