name: CI Workflow

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  static_code_analysis:
    uses:  PhenoAI/ci_cd_shared_infrastructure/.github/workflows/static_code_analysis_workflow.yml@main

  unit-tests:
    uses:  PhenoAI/ci_cd_shared_infrastructure/.github/workflows/unit_tests_workflow.yml@main

