name: Static Code Analysis Workflow

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  static-code-analysis-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: ./.github/actions/setup-python
      with:
        python-version: 3.11

    - name: Setup Python Dependencies
      uses: ./.github/actions/setup-python-dependencies

    - name: Run Black
      uses: ./.github/actions/black

    - name: Run Pylint
      uses: ./.github/actions/pylint

    - name: Run Isort
      uses: ./.github/actions/isort

    - name: Run Pycodestyle
      uses: ./.github/actions/pycodestyle

    - name: Run Flake8
      uses: ./.github/actions/flake8

    - name: Run MyPy
      uses: ./.github/actions/mypy

    - name: Run Bandit
      uses: ./.github/actions/bandit

    - name: Run Radon
      uses: ./.github/actions/radon
